In [1]:
import numpy as np

In [2]:
def some_code(Z):
    is_max = (
        (Z > np.roll(Z, 1, axis=0))
        & (Z > np.roll(Z, -1, axis=0))
        & (Z > np.roll(Z, 1, axis=1))
        & (Z > np.roll(Z, -1, axis=1))
        & (Z > np.roll(np.roll(Z, 1, axis=0), 1, axis=1))
        & (Z > np.roll(np.roll(Z, 1, axis=0), -1, axis=1))
        & (Z > np.roll(np.roll(Z, -1, axis=0), 1, axis=1))
        & (Z > np.roll(np.roll(Z, -1, axis=0), -1, axis=1))
    )
    return np.argwhere(is_max)

Z = np.array([
    [1, 2, 1],
    [3, 9, 4],
    [2, 5, 2]
])

maxima = some_code(Z)

In [5]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    b = (N == 3) & (Z[1:-1,1:-1]==0)
    s = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][b | s] = 1
    return Z

Z = np.random.randint(0,2,(5,5))
for i in range(10):
    print(Z)
    Z = iterate(Z)

[[0 1 0 0 0]
 [0 1 1 0 0]
 [1 0 1 1 1]
 [1 1 0 0 1]
 [1 0 1 0 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
import numpy as np

def iterate_torus(Z, m_rate=0.01):
    N = (np.roll(Z, +1, 0) + np.roll(Z, -1, 0) +
         np.roll(Z, +1, 1) + np.roll(Z, -1, 1) +
         np.roll(np.roll(Z, +1, 0), +1, 1) +
         np.roll(np.roll(Z, +1, 0), -1, 1) +
         np.roll(np.roll(Z, -1, 0), +1, 1) +
         np.roll(np.roll(Z, -1, 0), -1, 1))

    b = (N == 3) & (Z == 0)
    s = ((N == 2) | (N == 3)) & (Z == 1)
    Z_new = np.zeros_like(Z)
    Z_new[b | s] = 1

    m = np.random.rand(*Z.shape) < m_rate
    Z_new[m] = 1 - Z_new[m]

    return Z_new

def print_field(Z):
    chars = np.where(Z == 1, '▓', '░')
    print("\n".join(" ".join(row) for row in chars))

size = 12
steps = 20
m_rate = 0.02

Z = np.random.randint(0, 2, (size, size))

for step in range(steps):
    print_field(Z)
    print(f"Шаг {step+1}: значение — {Z.sum()}")
    Z = iterate_torus(Z, m_rate)
    print()

print("Готово!")

░ ░ ░ ▓ ▓ ░ ░ ░ ▓ ░ ░ ░
▓ ▓ ▓ ▓ ▓ ░ ▓ ░ ▓ ░ ░ ▓
░ ░ ░ ▓ ▓ ▓ ▓ ▓ ░ ▓ ▓ ░
▓ ░ ░ ░ ▓ ░ ░ ░ ▓ ░ ░ ░
░ ░ ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓ ▓ ░
░ ▓ ░ ░ ▓ ░ ▓ ░ ▓ ░ ░ ▓
░ ▓ ░ ▓ ░ ▓ ░ ░ ░ ░ ░ ▓
▓ ▓ ░ ░ ░ ▓ ░ ░ ░ ▓ ░ ▓
▓ ░ ▓ ▓ ░ ▓ ▓ ▓ ░ ▓ ░ ░
▓ ░ ▓ ░ ▓ ░ ▓ ▓ ▓ ▓ ░ ▓
▓ ░ ▓ ▓ ▓ ░ ░ ░ ▓ ░ ▓ ▓
▓ ░ ░ ░ ▓ ▓ ▓ ▓ ░ ░ ▓ ▓
Шаг 1: значение — 72

░ ░ ░ ░ ░ ░ ░ ░ ▓ ▓ ▓ ░
▓ ▓ ░ ░ ░ ░ ░ ░ ▓ ░ ▓ ▓
░ ░ ░ ░ ░ ░ ▓ ░ ░ ▓ ▓ ░
░ ░ ▓ ░ ░ ░ ░ ░ ░ ░ ░ ▓
▓ ▓ ▓ ░ ░ ░ ▓ ░ ░ ░ ▓ ▓
░ ▓ ░ ░ ░ ░ ▓ ░ ▓ ░ ░ ▓
░ ▓ ░ ░ ░ ▓ ▓ ░ ░ ▓ ░ ▓
░ ░ ░ ▓ ░ ▓ ░ ░ ▓ ░ ░ ▓
░ ░ ▓ ▓ ▓ ░ ░ ░ ░ ▓ ░ ░
░ ░ ░ ░ ░ ░ ░ ░ ░ ░ ░ ░
░ ░ ▓ ░ ░ ░ ░ ░ ░ ░ ░ ░
▓ ▓ ▓ ░ ░ ░ ▓ ▓ ▓ ░ ▓ ░
Шаг 2: значение — 44

░ ░ ▓ ░ ░ ░ ░ ░ ░ ░ ░ ░
▓ ░ ░ ░ ░ ░ ░ ▓ ▓ ░ ░ ░
░ ▓ ░ ░ ░ ░ ░ ░ ░ ▓ ░ ░
░ ░ ▓ ░ ░ ░ ░ ░ ░ ▓ ░ ░
░ ░ ▓ ░ ░ ░ ░ ▓ ░ ░ ▓ ░
░ ░ ░ ░ ░ ░ ▓ ░ ░ ▓ ░ ░
░ ░ ▓ ░ ▓ ▓ ▓ ░ ▓ ▓ ░ ▓
▓ ░ ░ ▓ ░ ▓ ▓ ░ ▓ ▓ ░ ░
░ ░ ▓ ▓ ▓ ░ ░ ░ ░ ░ ░ ░
▓ ░ ▓ ░ ░ ░ ░ ░ ░ ░ ░ ░
▓ ░ ▓ ░ ░ ░ ░ ▓ ░ ░ ░ ░
░ ▓ ▓ ░ ░ ░ ░ ▓ ▓ ░ ▓ ▓
Шаг 3: значение — 40

▓ ░ ▓ ░ ░ ░ ░ ░ ░ ▓ ░ ▓
░ ▓ ░ ░ ░ ░ ░ ░ ▓ ░ ░ ░
░ ▓ ░ ░ ░ ░ ░ ░ ░ ▓ ░ 